[files]
extend-exclude = [
	"release",
	# Optional system dependencies with git submodule fallback
	"subprojects/boost_math/math",
	"subprojects/qhull_r/libqhull_r",
	# Vendored with a script
	"subprojects/pyprima/pyprima",
	"scipy/_external/packaging_version/src",
	# Copied code, active upstream, changes made on the scipy side
	"scipy/optimize/_trlib",
	"scipy/sparse/linalg/_dsolve/SuperLU",
	# Copied code, active upstream, potentially outdated
	"scipy/_lib/_uarray",
	"scipy/_build_utils/tempita",
	"scipy/stats/libnpyrandom",
	"scipy/_lib/_docscrape.py",
	"scipy/io/_fast_matrix_market",
]

[default.extend-words]
aout = "aout"
arange = "arange"
aranges = "aranges"
asign = "asign"
ater = "ater"
ba = "ba"
Comput = "Comput"
cpy = "cpy"
datas = "datas"
delimitor = "delimitor"
delocate = "delocate"
filterd = "filterd"
fo = "fo"
gam = "gam"
indx = "indx"
iin = "iin"
iy = "iy"
iz = "iz"
maks = "maks"
mis = "mis"
Mor = "Mor"
nd = "nd"
nin = "nin"
nomes = "nomes"
numer = "numer"
numers = "numers"
Ome = "Ome"
ONO = "ONO"
Onn = "Onn"
ot = "ot"
padd = "padd"
parms = "parms"
Pn = "Pn"
sampl = "sampl"
scond = "scond"
ser = "ser"
siz = "siz"
Strang = "Strang"
srot = "srot"
Tak = "Tak"
thr = "thr"
tpe = "tpe"
ttest = "ttest"
ty = "ty"
ue = "ue"
vor = "vor"
wrk = "wrk"
desig= "desig"
forwrd = "forwrd"
inpt = "inpt"
TRU = "TRU"
chked = "chked"
yhat = "yhat"
yout = "yout"
bui = "bui"
alog = "alog"
giv = "giv"
Unser = "Unser"
alph = "alph"
boun = "boun"
curev = "curev"
Lyche = "Lyche"
workd = "workd"
equil = "equil"
correc = "correc"
alikes = "alikes"
aslo = "aslo"
Thm = "Thm"
dallocate = "dallocate"
lastr = "lastr"
reord = "reord"
lamda = "lamda"
UNEXPECT = "UNEXPECT"
Plas = "Plas"
hom = "hom"
aas = "aas"
oint = "oint"
ncrement = "ncrement"
zuser = "zuser"
cna = "cna"
expres = "expres"
HEPL = "HEPL"
HEL = "HEL"
Dorp = "Dorp"
Iinclude = "Iinclude"
Lenth = "Lenth"
grat = "grat"
ues = "ues"
addd = "addd"
Instituto = "Instituto"
updatd = "updatd"
formt = "formt"
NAM = "NAM"
iif = "iif"
Cours = "Cours"
Exercices = "Exercices"
nce = "nce"
FPT = "FPT"
dum = "dum"
Coninuous = "Coninuous"
adn = "adn"
anc= "anc"
HVE = "HVE"
SUBROUTIN = "SUBROUTIN"
writed = "writed"
ttests = "ttests"
orign = "orign"
Commun = "Commun"
PROJEC = "PROJEC"
Ist = "Ist"
tabl = "tabl"
IIT = "IIT"
Anwer = "Anwer"
explicits = "explicits"
Rade = "Rade"
Linke = "Linke"
Lond = "Lond"
setp = "setp"
Mathematisch = "Mathematisch"
Discrepance = "Discrepance"
Thie = "Thie"
SNET = "SNET"
multidimension = "multidimension"
thatn = "thatn"
trun = "trun"
CHEC = "CHEC"
ALS = "ALS"
uncompressible = "uncompressible"
whos = "whos"
sav = "sav"
Mak = "Mak"
boxs = "boxs"
roduct= "roduct"
continu = "continu"
Pinter = "Pinter"
restat = "restat"
UNIVERSITE = "UNIVERSITE"
RDER = "RDER"
utomatic = "utomatic"
IMPLCT = "IMPLCT"

nodel = "nodel"
